### ISSUE TITLE
Use json for players

### ISSUE THREAD

**Issue by denniske** [SiegeEngineers/aoc-reference-data#146]
I think json is easier to consume by clients than yaml, so I would like to change the players.yml to json. We can put the comments into a comment property like this:

```
- name: LaaaaaN
  country: es
  aoeelo: 62
  liquipedia: LaN
  esportsearnings: 56830
  aka:
    - LaN
  platforms:
    voobly:
      - "124116514" # ByT
      - "123989026" # Heresy
      - "124691590" # Jackie_Chan_
    rl:
      - "232410" # Antagonist
      - 196366-nac3 # Laaaaan
      - "1819193" # sheriff
      - "2602752"
      - "6892418"
  team: 21
  twitch:
    - https://www.twitch.tv/lan_aoe
  id: 8
  notability:
    aoe2: true
  discord_id: LaaaaaN#5576
```

becomes

```
{
    "name": "LaaaaaN",
    "country": "es",
    "aoeelo": 62,
    "liquipedia": "LaN",
    "esportsearnings": 56830,
    "aka": [
        "LaN"
    ],
    "platforms": {
        "voobly": [
            {id: "124116514", comment: 'ByT'},
            {id: "123989026", comment: 'Heresy'},
            {id: "124691590", comment: 'Jackie_Chan_'},
        ],
        "rl": [
            {id: "232410", comment: 'Antagonist'}
            {id: "196366-nac3", comment: 'Laaaaan'}
            {id: "1819193", comment: 'sheriff'}
            {id: "2602752"},
            {id: "6892418"},
        ]
    },
    "team": 21,
    "twitch": [
        "https://www.twitch.tv/lan_aoe"
    ],
    "id": 8,
    "notability": {
        "aoe2": true
    },
    "discord_id": "LaaaaaN#5576"
}
```
