### ISSUE TITLE
Unique constraint for `discord_id` failed

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#158]
```yaml
- name: A bao'
  country: vn
  platforms:
    rl:
      - "1743669"
    voobly:
      - "125010872"
  id: 400
  discord_id: Babaorum#3699
```

```yaml
- name: Babaorum
  country: fr
  platforms:
    rl:
      - "576919"
      - "3335279"
    voobly:
      - "123145914"
  liquipedia: Babaorum
  twitch:
    - https://www.twitch.tv/babaorum_aoe
  aoeelo: 851
  id: 233
  discord_id: Babaorum#3699
```
