### ISSUE TITLE
Unique constraint for `id: 594` failed 

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#159]
```yaml
- name: Dooidy
  country: cn
  platforms:
    rl:
      - '2594552'
  id: 594
  aoeelo: 1144
```
```yaml
- name: Terz
  country: de
  aoeelo: 1066
  platforms:
    rl:
      - '573282'
      - '15465466'
  discord_id: Terz#8397
  id: 594
  liquipedia: Terz
  twitch:
    - https://www.twitch.tv/terz_aoe
  team: 22
```
