### ISSUE TITLE
Unique constraint for `id: 613` failed 

### ISSUE THREAD

**Issue by simonsan** [SiegeEngineers/aoc-reference-data#160]
```yaml
- name: Ny4JyN
  country: br
  platforms:
    rl:
      - '2429762'
  id: 613
```
```yaml
- name: TeMo
  country: ma
  platforms:
    rl:
      - '6815493'
      - '12059289'
      - '14910497'
      - '14650521'
      - '15345163'
  id: 613
  aoeelo: 1322
